---
deployment:
  tasks:
    - export DEPLOYPATH=./../../public_html/advanced/
    - rsync -av --progress ./ $DEPLOYPATH --exclude .git
    - chmod 755 ./../../public_html/;
    - chmod 755 ./../../public_html/advanced/;
    - cd ./../../public_html/advanced/; /opt/cpanel/ea-php74/root/usr/bin/php -C /opt/cpanel/composer/bin/composer install
    - cd ./../../public_html/advanced/; /opt/cpanel/ea-php74/root/usr/bin/php -C /opt/cpanel/composer/bin/composer clearcache
    - cd ./../../public_html/advanced/; /opt/cpanel/ea-php74/root/usr/bin/php yii migrate --migrationPath=vendor/webvimark/module-user-management/migrations/ --interactive=0
    - cd ./../../public_html/advanced/; /opt/cpanel/ea-php74/root/usr/bin/php yii migrate --interactive=0
    - cd ./../../public_html/advanced/; /opt/cpanel/ea-php74/root/usr/bin/php yii cache/flush-all
    - cd ./../../public_html/advanced/; /opt/cpanel/ea-php74/root/usr/bin/php yii cache/flush-schema --interactive=0
